### ISSUE TITLE
Figure out proper TABs/spaces handling

### ISSUE THREAD

**Issue by abingham** [abingham/ponylang-mode#1]
The indentation function currently uses `indent-line-to` which will use TABs if `indent-tabs-mode` is enabled. Maybe this is all just fine, but I'd like to be sure. Figure out the proper way to do indentation that e.g. honors a user's whitespace settings.

**Comment by canweriotnow** [comment]
I've followed the reccommended `(set-variable 'indent-tabs-mode nil)` and I'm still getting crazy behavior with emacs re-tabbing things all wrong...

Maybe look at how the modes for Python or CoffeeScript handle this? Dunno.

**Comment by abingham** [comment]
Yeah, there is still some squirrely behavior in some cases. Can you give me an example of what you're seeing, maybe just a gist which exhibits the bad behavior (including a description)?

**Comment by canweriotnow** [comment]
Every time I hit enter after the first class or actor definition (even if I'm defining a new class or actor), it wants to indent the previous line 4-8 spaces, seemingly arbitrarily. then the next line starts indented 4-8 spaces, seemingly arbitrarily. If I go back and fix the indentation, I have to C-n to the next line instead of hitting RET or my indentation gets borked again. I don't have any special indentation settings in my config that aren't hooked to other major modes, so I don't think it's leakage...

I'll try to do a gist or perhaps even record my screen tonight or tomorrow for a better visual.

**Comment by abingham** [comment]
OK, I think I understand what you're saying. I'll poke around a bit and see what I can do.

**Comment by abingham** [comment]
In order to let the user `tab` through various indentation options, we'll need to keep a bit of state. I think it boils down to something like this:

  1. If the last thing typed was not a `tab`, then use the current algorithm to calculate indentation. It's pretty smart.
  2. If the last thing they typed *was* a `tab`, then we need to start cycling though other possible indentations.

One of the haskell indentation modes does something like a) cycle backwards until the beginning of the line is reached and then b) cycle forwards. We could do that.

The main trick, then, is adding a hook to see what the user is typing, looking for `tab`s. We then need to manage some state in response to that.

**Comment by abingham** [comment]
@canweriotnow Try out [the indentation branch](https://github.com/abingham/ponylang-mode/tree/indentation). It's not complete yet, but I think it's an improvement over the old system. I still need to add indentation cycling to the right, and I need some special handling for e.g. lines ending in "=".

**Comment by abingham** [comment]
OK, try out the master branch. I think things are working much better now. There are almost certainly still problems, so let me know as you find them. Thanks!
